### PR TITLE
Add parsing of contract abi types && Fix symbol precision bug

### PR DESCRIPTION
**Pull request by smlu**
Add missing abi number types and contract abi types parsing. Fix symbol precision format bug where symbol's precision length is 0.

### CODE REVIEW

**Comment by aaroncox** [comment]
Thanks for the PR! Adding more additional types to enable more contracts to perform properly is always a good step forward. 

Do you have an example contract/action where these types are used so we can test these out?

**Comment by lukap3rcic** [comment]
For token (fix symbol precision bug); jungle testnet, ram.token contract, symbol RAM

**Comment by smlu** [comment]
@aaroncox on jungle testnet you can test this PR with `turbotest123` smart contract. In this contract there are two actions `buy` and `sell` with type parameter `ttl_t` which is a type alias for int32

**Comment by aaroncox** [comment]
Confirmed, seems to work well. We'll merge this into develop and get it released with the next build.

**Pull request merged**
