### PR TITLE
Add regproxyinfo form

### PR DESCRIPTION
**Pull request by dafuga**
https://github.com/greymass/eos-voter/issues/281

### CODE REVIEW

**Comment by aaroncox** [comment]
Did a file get left out? Getting this when trying to run:

```
Module not found: Error: Can't resolve './Modal/ProxyInfo' in '/Users/aaron/projects/eos-voter-master/app/shared/components/Producers/Proxies'
 @ ./app/shared/components/Producers/Proxies/Table.js 19:17-45
 @ ./app/shared/components/Producers/Proxies.js
 @ ./app/shared/components/Producers.js
 @ ./app/shared/containers/BasicVoter.js
 @ ./app/renderer/basic/routes.js
 @ ./app/renderer/basic/index.js
 @ multi (webpack)-dev-server/client?http://localhost:1212 (webpack)/hot/dev-server.js react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/renderer/basic/index
```

**Comment by aaroncox** [comment]
Ahhhh you're on a case insensitive file system - check the casing on it ;)

**Comment by dafuga** [comment]
Yep, I think that's exactly it. Sorry about that!

**Comment by dafuga** [comment]
I'll push the fix first thing in the morning.

**Comment by aaroncox** [comment]
Some notes:

- What happened to putting the URL under the proxy name, just like on the BP page? It's in it's own column at the moment, which probably isn't needed. 
- The proxy information view is wrapped in a number of concentric segments, creating repeating borders around it. Can we remove a few of those so it's just one?
- The "Info on selected proxy:" looks out of place, it looks like it's expecting something after the `:`. 
- Maybe make the logo link clickable? 
- The search only does account name - think it should do this or the "name" field?

**Comment by dafuga** [comment]
Thanks! these should be quick changes so will get it all done tomorrow.

**Comment by dafuga** [comment]
@aaroncox Thanks for the feedback, made all those changes and I think you can take another look!

**Pull request merged**
