### PR TITLE
Update nodes.md

### PR DESCRIPTION
**Pull request by Drug0j**
- http://109.86.142.162:9876 - управляется [ exmotraderes ] (https://exmo.me/?ref=636896)

### CODE REVIEW

**Comment by aaroncox** [comment]
Going to reject this one since it has a referral link

**Comment by Drug0j** [comment]
nodes run echo http://82.144.198.169:9876/v1/chain/get_info

**Comment by Drug0j** [comment]
https://eosmeta.io/bpinfo/exmotraderes/

**Comment by Drug0j** [comment]
I beg to let my branch live as we are obliged to help each other 
see the history of the arbitrator
 and you will understand how much work was invested https://eosmeta.io/bpinfo/exmotraderes/.

**Comment by Drug0j** [comment]
see the history of the arbitrator
 and you will understand how much work was invested https://eosmeta.io/bpinfo/exmotraderes/.

**Pull request closed without merging**
