### PR TITLE
Add Dockerfile and build+run instructions

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by aaroncox** [comment]
This is a really cool way to use docker, I didn't even realize you could forward display elements like this.

I'm digging into how it works and testing it out over the next day or two, we'll try to get this merged in for our next minor release.

**Comment by kargakis** [comment]
@aaroncox thanks for looking into this. I can't build eos-voter on my host because of the following error and yarn brings in a ton of dependencies so having a docker build is convenient.

```
$ yarn install
Error: Could not find or load main class install
```

**Comment by kargakis** [comment]
The only thing I think is missing from this is to update the instructions to bind-mount (-v) keys and whatever other state eos-voter needs in order to operate correctly. Unfortunately I am not familiar with that part of the wallet yet.

**Comment by aaroncox** [comment]
`$XDG_CONFIG_HOME or ~/.config on Linux`

I think that's probably the only path that'd end up needing mapped to persist/store the data, the settings + wallet + logs are written to that folder on Linux builds.

On a side note, I spent a couple hours playing with the docker container version and was trying to get it working on macOS + Linux Docker container + XQuartz. I haven't gotten it working yet, but I imagine it's possible. Feature work on the wallet took priority though and I haven't had a chance to revisit.

**Comment by kargakis** [comment]
Going to close as I don't have any time to push this forward and need to get it out of my PR list. Feel free to copy what I have and continue if you want it.

**Pull request closed without merging**
