### PR TITLE
Add KOY mainnet & testnet

### PR DESCRIPTION
**Pull request by JPBeukes**
This PR resolves issue #1371: Add the KOY mainnet and testnet to the Anchor wallet.

Note:
- We disabled RAM markets feature
- A single logo is used for both mainnet and testnet, but we are open to creating a separate testnet logo if necessary.

Team Greymass, thanks in advance! You guys are doing amazing work, and we salute you for it! 🫡

### CODE REVIEW

**Comment by JPBeukes** [comment]
Also note that I didn't run any tests on the changes. Please let me know if you need anything else from me 🙂

**Comment by sandroguras** [comment]
Thank you for your contribution @JPBeukes. We will review your PR shortly.

**Comment by aaroncox** [comment]
Looks good, we'll merge it in. 

We have no ETA on the next update of the Anchor Desktop app, but this will be included during that next release.

**Comment by JPBeukes** [comment]
Thanks @aaroncox! Looking forward to it! All the best.

**Pull request merged**
